const DOM = {};
const AppState = { dream: '', mood: '', style: 'psychology', currentContent: '', records: [] };
function initDOM() { DOM.dreamInput = document.getElementById('dream-input'); DOM.mood = document.getElementById('mood'); DOM.style = document.getElementById('style'); DOM.btnInterpret = document.getElementById('btn-interpret'); DOM.resultArea = document.getElementById('result-area'); DOM.content = document.getElementById('content'); DOM.historyPanel = document.getElementById('history-panel'); DOM.historyList = document.getElementById('history-list'); DOM.historyOverlay = document.getElementById('history-overlay'); DOM.settingsModal = document.getElementById('settings-modal'); DOM.toast = document.getElementById('toast'); }
function initEvents() {
    DOM.dreamInput.addEventListener('input', () => AppState.dream = DOM.dreamInput.value);
    DOM.mood.addEventListener('change', () => AppState.mood = DOM.mood.value);
    DOM.style.addEventListener('change', () => AppState.style = DOM.style.value);
    DOM.btnInterpret.addEventListener('click', interpret);
    document.getElementById('btn-save').addEventListener('click', saveRecord);
    document.getElementById('btn-history').addEventListener('click', () => { DOM.historyPanel.classList.add('open'); DOM.historyOverlay.classList.remove('hidden'); });
    document.getElementById('btn-close-history').addEventListener('click', closeHistory); DOM.historyOverlay.addEventListener('click', closeHistory);
    document.getElementById('btn-settings').addEventListener('click', () => { DOM.settingsModal.classList.add('show'); loadSettings(); });
    document.getElementById('btn-close-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-cancel-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-save-settings').addEventListener('click', saveSettings);
    document.querySelectorAll('.example-btn').forEach(btn => btn.addEventListener('click', () => loadExample(btn.dataset.example)));
}
const EXAMPLES = { fly: { dream: '我梦见自己在天空中自由飞翔，感觉非常轻盈自在，可以看到下面的城市和山川...', mood: 'happy' }, fall: { dream: '我梦见自己从很高的地方掉下去，一直在坠落，非常害怕，快要落地的时候就醒了...', mood: 'scared' }, chase: { dream: '我梦见被不明的东西追赶，不停地跑但总是跑不快，很紧张...', mood: 'anxious' }, teeth: { dream: '我梦见自己的牙齿一颗一颗掉落，感觉很慌张...', mood: 'anxious' } };
function loadExample(key) { const ex = EXAMPLES[key]; if (!ex) return; DOM.dreamInput.value = ex.dream; AppState.dream = ex.dream; DOM.mood.value = ex.mood; AppState.mood = ex.mood; showToast('info', '已填入', '点击解读梦境'); }
async function interpret() { if (!AppState.dream.trim()) { showToast('warning', '请描述梦境', ''); return; } DOM.resultArea.classList.remove('hidden'); DOM.content.innerHTML = ''; AppState.currentContent = ''; await AIService.interpret(AppState.dream, AppState.mood, AppState.style, (t) => { AppState.currentContent += t; DOM.content.innerHTML = formatContent(AppState.currentContent); }, () => showToast('success', '解读完成', ''), (e) => showToast('error', '解读失败', e.message)); }
function formatContent(text) { return text.replace(/^## (.+)$/gm, '<h2 class="text-lg font-bold text-purple-300 mt-5 mb-2">$1</h2>').replace(/\*\*(.+?)\*\*/g, '<strong class="text-indigo-300">$1</strong>').replace(/\n/g, '<br>'); }
async function saveRecord() { if (!AppState.currentContent) { showToast('warning', '无内容', ''); return; } const record = { dream: AppState.dream.substring(0, 50) + '...', content: AppState.currentContent }; const result = await StorageService.saveRecord(record); if (result.success) { showToast('success', '已保存', ''); loadHistory(); } }
async function loadHistory() { AppState.records = await StorageService.getRecords(); renderHistory(); }
function renderHistory() { if (AppState.records.length === 0) { DOM.historyList.innerHTML = '<p class="text-purple-400/50 text-sm text-center">暂无记录</p>'; return; } DOM.historyList.innerHTML = AppState.records.map(r => `<div class="p-3 bg-purple-800/30 rounded-xl"><div class="font-medium text-purple-200 text-ellipsis overflow-hidden whitespace-nowrap">🌙 ${r.dream}</div><div class="text-xs text-purple-400/70 mt-1">${new Date(r.createdAt).toLocaleDateString()}</div></div>`).join(''); }
function closeHistory() { DOM.historyPanel.classList.remove('open'); DOM.historyOverlay.classList.add('hidden'); }
function loadSettings() { const c = AIService.getModelConfig() || {}; document.getElementById('api-url').value = c.apiUrl || ''; document.getElementById('api-key').value = c.apiKey || ''; document.getElementById('model-name').value = c.modelName || ''; }
function saveSettings() { const c = { apiUrl: document.getElementById('api-url').value.trim(), apiKey: document.getElementById('api-key').value.trim(), modelName: document.getElementById('model-name').value.trim() || 'GLM-4-Flash' }; if (!c.apiUrl || !c.apiKey) { showToast('warning', '请填写完整', ''); return; } AIService.saveModelConfig(c); DOM.settingsModal.classList.remove('show'); showToast('success', '配置已保存', ''); }
function showToast(type, title, message) { const icons = { success: '✅', error: '❌', warning: '⚠️', info: 'ℹ️' }; const colors = { success: 'bg-green-500', error: 'bg-red-500', warning: 'bg-yellow-500', info: 'bg-purple-500' }; document.getElementById('toast-icon').className = `w-8 h-8 rounded-full flex items-center justify-center ${colors[type]}`; document.getElementById('toast-icon').textContent = icons[type]; document.getElementById('toast-title').textContent = title; document.getElementById('toast-message').textContent = message; DOM.toast.classList.remove('hidden'); setTimeout(() => DOM.toast.classList.add('hidden'), 3000); }
async function init() { initDOM(); initEvents(); await loadHistory(); const config = await AIService.initConfig(); if (!config) setTimeout(() => { DOM.settingsModal.classList.add('show'); showToast('info', '欢迎使用', '请配置 AI 模型'); }, 500); }
document.addEventListener('DOMContentLoaded', init);
